[build-system]
requires = ["scikit-build-core>=0.10.0", "cmake>=3.15", "ninja"]
build-backend = "scikit_build_core.build"

[project]
name = "chronos"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.scikit-build]
wheel.packages = ["python/chronos"]
cmake.args = ["-DNB_DIR=third_party/nanobind"]